steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/quickstart-image:$REVISION_ID', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/quickstart-image:$REVISION_ID"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - 'deployment/my-app'
  - 'quickstart-image=gcr.io/$PROJECT_ID/quickstart-image:$REVISION_ID'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=my-cluster'