apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cloud-app
  labels:
    app: my-cloud-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
      - name: myweb
        image: myweb:latest
        ports:
        - containerPort: 9000